(deftheme mbacou
  "Created 2013-03-25.")

(custom-theme-set-variables
 'mbacou
 '(ansi-term-color-vector [unspecified "#555555" "#a40000" "#61862F" "#c4a000" "#204a87" "#7653C1" "#4C8FC7" "#ECECEC"]))

(custom-theme-set-faces
 'mbacou
 '(show-paren-match ((t (:background "#eeeeee"))))
 '(vertical-border ((nil (:foreground "#C4C4C4"))))
 '(cursor ((t (:background "#4AF8F8"))))
 '(fringe ((t (:background "#f8f8f8" :foreground "#C4C4C4" :slant oblique))))
 '(highlight ((t (:background "#edf8f8"))))
 '(region ((t (:background "#BFF8F8"))))
 '(secondary-selection ((t (:background "#8cc4ff"))))
 '(isearch ((t (:background "#FFE792" :foreground "#000000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#e9b96e"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ef2929"))))
 '(mode-line-inactive ((t (:background "#6B6F79" :foreground "#f8f8f8" :box (:line-width 2 :color "#6B6F79")))))
 '(mode-line ((t (:background "#414856" :foreground "#f8f8f8" :box (:line-width 2 :color "#414856")))))
 '(minibuffer-prompt ((t (:foreground "#204a87" :weight bold))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ce5c00"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#4e9a06"))))
 '(bm-fringe-persistent-face ((t (:foreground "#C4C4C4" :background "#ECECEC" ))))
 '(bm-fringe-face ((t (:foreground "#C4C4C4" :background "#ECECEC" ))))

 '(font-lock-builtin-face ((t (:foreground "#7653C1"))))
 '(font-lock-comment-face ((t (:foreground "#ADADAD" :slant italic))))
 '(font-lock-constant-face ((t (:weight semi-bold))))
 '(font-lock-delimiters-face ((t (:weight semi-bold))))
 '(font-lock-function-name-face ((t (:foreground "#61862F" :weight semi-bold))))
 '(font-lock-keyword-face ((t (:foreground "#7653C1" :weight normal))))
 '(font-lock-string-face ((t (:foreground "#BC670F"))))
 '(font-lock-type-face ((t (:foreground "#204a87"))))
 '(font-lock-variable-name-face ((t (:foreground "#4C8FC7"))))
 '(ess-numbers-face ((t (:foreground "#61862F"))))
 '(ein:cell-input-area ((t (:background "grey90"))))
 '(ein:cell-input-prompt ((t (:background "#607D8B" :foreground "#ffffff"))))
 
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#204a87"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#3465a4"))))

 '(helm-source-header ((t (:height 1.2 :weight bold :foreground "#546E7A"))))
 '(helm-visible-mark ((t (:background "#37ABC8" :foreground "#F8F8F8"))))
 '(helm-selection ((t (:background "#BFF8F8" :foreground "#000000"))))
 '(helm-selection-line ((t (:background "#edf8f8"))))
 '(helm-M-x-key ((t (:foreground "#ADADAD"))))
 '(helm-match ((t (:foreground "#BC670F"))))

 '(gnus-header-name ((t (:weight normal :foreground "#ADADAD"))))
 '(gnus-header-subject ((t (:weight normal :foreground "#7653C1"))))
 '(gnus-header-content ((t (:weight normal :foreground "#7653C1"))))
 '(gnus-button ((t (:weight normal :foreground "#7653C1"))))
 '(gnus-header-date ((t (:weight normal :foreground "#7653C1"))))
 '(gnus-group-news-1 ((t (:weight bold :foreground "#5c3566"))))
 '(gnus-group-news-2 ((t (:weight bold :foreground "#204a87"))))
 '(gnus-group-news-3 ((t  (:weight bold :foreground "#a40000"))))
 '(gnus-group-news-4 ((t (:weight bold :foreground "#7a4c02"))))
 '(gnus-group-news-5 ((t (:weight bold :foreground "#ce5c00"))))
 '(gnus-group-news-low ((t (:foreground "#888a85"))))
 '(gnus-group-mail-1 ((t (:weight bold :foreground "#5c3566"))))
 '(gnus-group-mail-2 ((t (:weight bold :foreground "#204a87"))))
 '(gnus-group-mail-3 ((t (:foreground "#61862F" :weight bold))))
 '(gnus-group-mail-low ((t (:foreground "#888a85"))))
 '(message-header-name ((t (:foreground "#204a87"))))
 '(message-header-cc ((t (:foreground "#c4a000"))))
 '(message-header-other ((t (:foreground "#c17d11"))))
 '(message-header-subject ((t (:foreground "#a40000"))))
 '(message-header-to ((t (:weight bold :foreground "#c4a000"))))
 '(message-cited-text ((t (:slant italic :foreground "#5f615c"))))
 '(message-separator ((t (:foreground "#61862F" :weight bold))))

 '(org-agenda-date ((t (:foreground "#7653C1"))))
 '(org-agenda-done ((t (:foreground "#4e9a06" :weight normal))))
 '(org-agenda-structure ((t (:foreground "#7653C1" :weight semi-bold))))
 '(org-agenda-todo ((t (:foreground "#a40000" :weight normal))))
 '(org-block-background ((t (:background "#d3d7cf"))))
 '(org-block-begin-line ((t (:weight bold :foreground "#008ED1"))))
 '(org-block-end-line ((t (:weight semi-bold :foreground "#008ED1"))))
 '(org-category ((t (:height 0.9 :foreground "#204a87" ))))
 '(org-checkbox-statistics-todo ((t (:height 0.9 :foreground "#ADADAD" :background "ivory2" :slant italic))))
 '(org-date ((t (:foreground "#7653C1"))))
 '(org-deadline ((t (:foreground "#555555" :weight normal))))
 '(org-scheduled ((t (:foreground "#555555" :weight normal))))
 '(org-document-info ((t (:foreground "#555555" :weight semi-bold))))
 '(org-document-title ((t (:foreground "#555555" :weight semi-bold))))
 '(org-done ((t (:foreground "#4e9a06" :weight normal))))
 '(org-formula ((t (:height 0.9 :foreground "#7653C1" :slant italic))))
 '(org-level-1 ((t (:weight semi-bold :foreground "#555555"))))
 '(org-level-2 ((t (:weight semi-bold :foreground "#555555"))))
 '(org-level-3 ((t (:foreground "#555555" :weight normal :slant italic))))
 '(org-level-4 ((t (:foreground "#555555" :weight normal :slant italic))))
 '(org-level-5 ((t (:foreground "#555555" :weight normal :slant italic))))
 '(org-link ((t (:foreground "#204a87" :underline t))))
 '(org-special-keyword ((t (:foreground "#ADADAD" :slant italic :weight normal))))
 '(org-property-value ((t (:foreground "#ADADAD" :slant italic :weight normal))))
 '(org-tag ((t (:height 0.9 :background "ivory2" :foreground "#ADADAD" :slant normal :weight semi-bold))))
 '(org-todo ((t (:foreground "#a40000" :weight normal))))
 '(org-upcoming-deadline ((t (:foreground "#555555"))))
 '(org-warning ((t (:foreground "#555555" :weight semi-bold))))
 '(table-cell ((t (:foreground "#555555" :inverse-video nil))))

 '(ecb-bucket-node-face ((t (:inherit ecb-default-general-face :weight semi-bold))))
 '(ecb-default-general-face ((t (:foreground "#555555" :height 1.0 :family "M+ 1mn"))))
 '(ecb-default-highlight-face ((t (:background "#edf8f8" :foreground "#555555"))))
 '(ecb-method-face ((t (:inherit ecb-default-highlight-face))))
 '(ecb-mode-line-prefix-face ((t (:foreground "#555555"))))
 '(ecb-tag-header-face ((t (:background "#edf8f8"))))

 '(speedbar-directory-face ((t (:foreground "#555555" :weight semi-bold))))
 '(speedbar-separator-face ((t (:foreground "#555555" :background "#f8f8f8" :weight normal :slant italic))))
 '(speedbar-file-face ((t (:foreground "#555555"))))
 '(speedbar-tag-face ((t (:foreground "#61862F"))))
 '(speedbar-button-face ((t (:foreground "#888a85"))))
 '(speedbar-selected-face ((t (:foreground "#7653C1"))))
 '(speedbar-highlight-face ((t (:background "#BFF8F8"))))

 '(default ((t (:background "#f8f8f8" :foreground "#555555")))))

;;;###autoload
(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))

(provide-theme 'mbacou)
